---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Setting up the foundation"
      solveButton: false
    - name: module-02
      label: "Domains for the multidomain"
      solveButton: false
    - name: module-03
      label: "Deploy the WebApps!"
      solveButton: false

tabs:
  - name: aap
    url: https://control-${guid}.${domain}/
    external: false
  - name: Domain Controller
    url: https://windows-ironrdp-${guid}.${domain}/
    external: false
  - name: Database Server
    url: https://dbserver-ironrdp-${guid}.${domain}/
    external: false
  - name: Webapp-windows
    url: https://dbserver-${guid}.${domain}/
    external: false
  - name: Webapp-rhel
    url: https://node01-${guid}.${domain}/
    external: false
  - name: loadbalancer
    url: https://haproxy-${guid}.${domain}/
    external: false
