---
# By default egress traffic is not allowed, define below the ports allowed.
ingress:
- ports:
  - protocol: TCP
    port: 443
  - protocol: TCP
    port: 80
  - protocol: TCP
    port: 3000
  - protocol: TCP
    port: 22
  - protocol: TCP
    port: 5986
  - protocol: TCP
    port: 3389
  - protocol: TCP
    port: 389
  - protocol: TCP
    port: 445
  - protocol: TCP
    port: 138
  - protocol: TCP
    port: 139
  - protocol: UDP
    port: 53
egress:
- {}
- ports:
  - protocol: TCP
    port: 443
  - protocol: TCP
    port: 80
  - protocol: TCP
    port: 3000
  - protocol: TCP
    port: 22
  - protocol: TCP
    port: 5986
  - protocol: TCP
    port: 3389
  - protocol: TCP
    port: 389
  - protocol: TCP
    port: 445
  - protocol: TCP
    port: 138
  - protocol: TCP
    port: 139
  - protocol: UDP
    port: 53
